In [4]:
import pandas as pd
import numpy as np

In [2]:
pip install pandas

Collecting pandas
  Using cached pandas-3.0.5-cp312-cp312-win_amd64.whl.metadata (19 kB)
Collecting numpy>=1.26.0 (from pandas)
  Using cached numpy-2.5.2-cp312-cp312-win_amd64.whl.metadata (6.6 kB)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\ayham\appdata\roaming\python\python312\site-packages (from pandas) (2.9.0.post0)
Collecting tzdata (from pandas)
  Using cached tzdata-2026.3-py2.py3-none-any.whl.metadata (1.4 kB)
Requirement already satisfied: six>=1.5 in c:\users\ayham\appdata\roaming\python\python312\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Using cached pandas-3.0.5-cp312-cp312-win_amd64.whl (9.8 MB)
Using cached numpy-2.5.2-cp312-cp312-win_amd64.whl (12.5 MB)
Using cached tzdata-2026.3-py2.py3-none-any.whl (348 kB)
Installing collected packages: tzdata, numpy, pandas
Successfully installed numpy-2.5.2 pandas-3.0.5 tzdata-2026.3
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 25.0.1 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [3]:
pip install pandas

Requirement already satisfied: pandas in c:\users\ayham\appdata\local\programs\python\python312\lib\site-packages (3.0.5)
Requirement already satisfied: numpy>=1.26.0 in c:\users\ayham\appdata\local\programs\python\python312\lib\site-packages (from pandas) (2.5.2)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\ayham\appdata\roaming\python\python312\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in c:\users\ayham\appdata\local\programs\python\python312\lib\site-packages (from pandas) (2026.3)
Requirement already satisfied: six>=1.5 in c:\users\ayham\appdata\roaming\python\python312\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 25.0.1 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [8]:
df= pd.read_csv("../data/dans-ma-rue.csv", sep=";")

In [10]:
df.head(10)

,numero,type,soustype,adresse,code_postal,ville,arrondissement,conseilquartier,datedecl,anneedecl,moisdecl,prefixe,intervenant,id_dmr,geo_shape,geo_point_2d,mois_annee_decla
0,89946,Objets abandonnés,Autres objets encombrants abandonnés,"16 rue Victor Duruy, 75015 PARIS",75015.0,Paris 15,15,ALLERAY - PROCESSION,2025-06-16,2025,6,Page DMR Paris.fr,DPE-STPP-DT,S2025F089946,"{""coordinates"": [2.2988817998435738, 48.837089...","48.837089999362114, 2.2988817998435738",2025-06
1,46828,"Graffitis, tags, affiches et autocollants","Graffitis et autocollants sur mur, façade sur ...","31 Boulevard Saint-Jacques, 75014 PARIS",75014.0,Paris 14,14,MONTSOURIS - DAREAU,2025-01-10,2025,1,Android,graffitis,G2025A046828,"{""coordinates"": [2.338363600256627, 48.8323799...","48.8323799990552, 2.338363600256627",2025-01
2,98544,Objets abandonnés,Autres objets encombrants abandonnés,"2 Rue d'Orsel, 75018 PARIS",75018.0,Paris 18,18,MONTMARTRE,2025-06-18,2025,6,IOS application,DPE-STPP-DT,A2025F098544,"{""coordinates"": [2.3469159994878956, 48.883829...","48.88382999937114, 2.3469159994878956",2025-06
3,150481,Propreté,Propreté des équipements de collecte des déche...,"63 Quai de la Seine, 75019 PARIS",75019.0,Paris 19,19,BASSIN DE LA VILLETTE,2025-03-27,2025,3,Android,SULO,G2025C150481,"{""coordinates"": [2.376401400033495, 48.8877999...","48.88779999900783, 2.376401400033495",2025-03
4,155897,Activités commerciales et professionnelles,Étalages et terrasses à usage commercial : Ter...,"8 Boulevard de Bonne Nouvelle, 75010 PARIS",75010.0,Paris 10,10,PORTE SAINT-DENIS - PARADIS,2025-03-28,2025,3,IOS application,DPMP-Divisions,A2025C155897,"{""coordinates"": [2.3522377000302304, 48.870036...","48.87003699901961, 2.3522377000302304",2025-03
5,5802,"Graffitis, tags, affiches et autocollants","Affiches, autocollants ou graffitis sur mobili...","55 Avenue de Breteuil, 75007 PARIS",75007.0,Paris 07,7,ECOLE MILITAIRE,2025-05-02,2025,5,Android,graffitis,G2025E005802,"{""coordinates"": [2.3120936993353682, 48.848719...","48.84871999886914, 2.3120936993353682",2025-05
6,20562,"Graffitis, tags, affiches et autocollants","Affiches, autocollants ou graffitis sur mobili...","1 boulevard de la Chapelle, 75010 PARIS",75010.0,Paris 10,10,LOUIS BLANC - AQUEDUC,2025-08-05,2025,8,Android,graffitis,G2025H020562,"{""coordinates"": [2.3640312997201596, 48.884173...","48.88417399882509, 2.3640312997201596",2025-08
7,37776,"Graffitis, tags, affiches et autocollants","Graffitis et autocollants sur mur, façade sur ...","11 Rue de Meaux, 75019 PARIS",75019.0,Paris 19,19,SECRETAN,2026-03-07,2026,3,IOS application,graffitis,A2026C037776,"{""coordinates"": [2.3710159995078683, 48.878779...","48.87877999922023, 2.3710159995078683",2026-03
8,144520,Mobiliers urbains,Autres : Jardinière ou bac détériorée,"61 Rue Duhesme, 75018 PARIS",75018.0,Paris 18,18,CLIGNANCOURT - JULES JOFFRIN,2025-04-27,2025,4,IOS application,DEVE,A2025D144520,"{""coordinates"": [2.3422009993573516, 48.893191...","48.89319199914779, 2.3422009993573516",2025-04
9,6520,Objets abandonnés,Cartons ou sacs de déchets ménagers,"47 Rue de Vouillé, 75015 PARIS",75015.0,Paris 15,15,ALLERAY - PROCESSION,2026-04-02,2026,4,IOS application,DPE-STPP-DT,A2026D006520,"{""coordinates"": [2.3084216000959494, 48.833969...","48.83396999900218, 2.3084216000959494",2026-04

In [12]:
df.shape

(1474285, 17)

In [14]:
df.columns

Index(['numero', 'type', 'soustype', 'adresse', 'code_postal', 'ville',
       'arrondissement', 'conseilquartier', 'datedecl', 'anneedecl',
       'moisdecl', 'prefixe', 'intervenant', 'id_dmr', 'geo_shape',
       'geo_point_2d', 'mois_annee_decla'],
      dtype='str')

In [16]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1474285 entries, 0 to 1474284
Data columns (total 17 columns):
 #   Column            Non-Null Count    Dtype
---  ------            --------------    -----
 0   numero            1474285 non-null  int64
 1   type              1474285 non-null  str
 2   soustype          1474281 non-null  str
 3   adresse           1474285 non-null  str
 4   code_postal       1474282 non-null  float64
 5   ville             1474285 non-null  str
 6   arrondissement    1474285 non-null  int64
 7   conseilquartier   1474174 non-null  str
 8   datedecl          1474285 non-null  str
 9   anneedecl         1474285 non-null  int64
 10  moisdecl          1474285 non-null  int64
 11  prefixe           1474285 non-null  str
 12  intervenant       1474283 non-null  str
 13  id_dmr            1474285 non-null  str
 14  geo_shape         1474285 non-null  str
 15  geo_point_2d      1474285 non-null  str
 16  mois_annee_decla  1474285 non-null  str
dtypes: float64(1), int64(4), str(12)
memory usage: 191.2 MB

In [17]:
df.dtypes

numero                int64
type                    str
soustype                str
adresse                 str
code_postal         float64
ville                   str
arrondissement        int64
conseilquartier         str
datedecl                str
anneedecl             int64
moisdecl              int64
prefixe                 str
intervenant             str
id_dmr                  str
geo_shape               str
geo_point_2d            str
mois_annee_decla        str
dtype: object

In [19]:
df.isnull().sum()

numero                0
type                  0
soustype              4
adresse               0
code_postal           3
ville                 0
arrondissement        0
conseilquartier     111
datedecl              0
anneedecl             0
moisdecl              0
prefixe               0
intervenant           2
id_dmr                0
geo_shape             0
geo_point_2d          0
mois_annee_decla      0
dtype: int64

In [20]:
df.value_counts()

numero  type                                        soustype                                                                            adresse                                     code_postal  ville     arrondissement  conseilquartier              datedecl    anneedecl  moisdecl  prefixe            intervenant     id_dmr        geo_shape                                                                   geo_point_2d                            mois_annee_decla
89946   Objets abandonnés                           Autres objets encombrants abandonnés                                                16 rue Victor Duruy, 75015 PARIS            75015.0      Paris 15  15              ALLERAY - PROCESSION         2025-06-16  2025       6         Page DMR Paris.fr  DPE-STPP-DT     S2025F089946  {"coordinates": [2.2988817998435738, 48.837089999362114], "type": "Point"}  48.837089999362114, 2.2988817998435738  2025-06             1
46828   Graffitis, tags, affiches et autocollants   Graffitis et autocollants sur mur, façade sur rue, pont et descente d'eau pluviale  31 Boulevard Saint-Jacques, 75014 PARIS     75014.0      Paris 14  14              MONTSOURIS - DAREAU          2025-01-10  2025       1         Android            graffitis       G2025A046828  {"coordinates": [2.338363600256627, 48.8323799990552], "type": "Point"}     48.8323799990552, 2.338363600256627     2025-01             1
98544   Objets abandonnés                           Autres objets encombrants abandonnés                                                2 Rue d'Orsel, 75018 PARIS                  75018.0      Paris 18  18              MONTMARTRE                   2025-06-18  2025       6         IOS application    DPE-STPP-DT     A2025F098544  {"coordinates": [2.3469159994878956, 48.88382999937114], "type": "Point"}   48.88382999937114, 2.3469159994878956   2025-06             1
150481  Propreté                                    Propreté des équipements de collecte des déchets : Trilib' sale ou dégradé          63 Quai de la Seine, 75019 PARIS            75019.0      Paris 19  19              BASSIN DE LA VILLETTE        2025-03-27  2025       3         Android            SULO            G2025C150481  {"coordinates": [2.376401400033495, 48.88779999900783], "type": "Point"}    48.88779999900783, 2.376401400033495    2025-03             1
155897  Activités commerciales et professionnelles  Étalages et terrasses à usage commercial : Terrasse sale ou dégradée                8 Boulevard de Bonne Nouvelle, 75010 PARIS  75010.0      Paris 10  10              PORTE SAINT-DENIS - PARADIS  2025-03-28  2025       3         IOS application    DPMP-Divisions  A2025C155897  {"coordinates": [2.3522377000302304, 48.87003699901961], "type": "Point"}   48.87003699901961, 2.3522377000302304   2025-03             1
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 ..
103606  Graffitis, tags, affiches et autocollants   Graffitis et autocollants sur mur, façade sur rue, pont et descente d'eau pluviale  21 Rue Titon, 75011 PARIS                   75011.0      Paris 11  11              NATION - ALEXANDRE DUMAS     2026-02-19  2026       2         IOS application    graffitis       A2026B103606  {"coordinates": [2.3861839995559673, 48.85211999887924], "type": "Point"}   48.85211999887924, 2.3861839995559673   2026-02             1
41084   Objets abandonnés                           Autres objets encombrants abandonnés                                                16 Avenue Léon Bollée, 75013 PARIS          75013.0      Paris 13  13              ITALIE - PEUPLIERS - RUNGIS  2026-03-08  2026       3         Android            DPE-STPP-DT     G2026C041084  {"coordinates": [2.3631889995276083, 48.81820699902852], "type": "Point"}   48.81820699902852, 2.3631889995276083   2026-03             1
91391   Graffitis, tags, affiches et autocollants   Graffitis et autocollants sur mur, façade sur rue, pont et descente d'eau pluviale  236 Boulevard Voltaire, 75011 PARIS         75011.0      Paris 11  11              NATION - ALEXANDRE DUMAS     2025-12-16  2025       12        IOS application    graffitis       A2025L091391  {"coordinates": [2.3900670000323796, 48.8516849988838], "type": "Point"}    48.8516849988838, 2.3900670000323796    2025-12             1
81005   Objets abandonnés                           Autres objets encombrants abandonnés                                                2 Rue Emeriau, 75015 PARIS                  75015.0      Paris 15  15              DUPLEIX - LA MOTTE PICQUET   2025-01-16  2025       1         Android            DPE-STPP-DT     G2025A081005  {"coordinates": [2.2883464998181893, 48.85203999910214], "type": "Point"}   48.85203999910214, 2.2883464998181893   2025-01             1
75205   Graffitis, tags, affiches et autocollants   Graffitis et autocollants sur mur, façade sur rue, pont et descente d'eau pluviale  199 Rue du Chevaleret, 75013 PARIS          75013.0      Paris 13  13              SALPETRIERE - AUSTERLITZ     2025-03-14  2025       3         IOS application    graffitis       A2025C075205  {"coordinates": [2.367361000172781, 48.834353999327], "type": "Point"}      48.834353999327, 2.367361000172781      2025-03             1
Name: count, Length: 1474165, dtype: int64

In [21]:
df.mode()

,numero,type,soustype,adresse,code_postal,ville,arrondissement,conseilquartier,datedecl,anneedecl,moisdecl,prefixe,intervenant,id_dmr,geo_shape,geo_point_2d,mois_annee_decla
0,125.0,Objets abandonnés,Autres objets encombrants abandonnés,"Bois de Vincennes Route de la Pyramide, 75012 ...",75018.0,Paris 18,18.0,BELLEVILLE,2025-06-02,2025.0,3.0,Android,DPE-STPP-DT,A2025A000005,"{""coordinates"": [2.360248999507263, 48.8555869...","48.85558699931011, 2.360248999507263",2025-03
1,153.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,A2025A000006,NaN,NaN,NaN
2,154.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,A2025A000007,NaN,NaN,NaN
3,160.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,A2025A000009,NaN,NaN,NaN
4,163.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,A2025A000015,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1474280,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,S2026E106456,NaN,NaN,NaN
1474281,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,S2026E106459,NaN,NaN,NaN
1474282,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,S2026E106462,NaN,NaN,NaN
1474283,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,S2026E106507,NaN,NaN,NaN
1474284,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,S2026E106514,NaN,NaN,NaN

In [22]:
df.value_counts().max()

np.int64(1)

In [23]:
# Affiche uniquement le nombre maximal de répétitions pour chaque colonne
df.apply(lambda x: x.value_counts().max())

numero                   17
type                 631217
soustype             496733
adresse                 835
code_postal          133051
ville                132190
arrondissement       132190
conseilquartier       35088
datedecl               4412
anneedecl           1060484
moisdecl             193549
prefixe              893415
intervenant          883737
id_dmr                    1
geo_shape               320
geo_point_2d            320
mois_annee_decla      97378
dtype: int64

In [24]:

df['ville'].value_counts()

ville
Paris 18    132190
Paris 20    131858
Paris 17    125147
Paris 15    121025
Paris 19    113396
Paris 11    112121
Paris 10    105243
Paris 12     88825
Paris 13     80375
Paris 16     76525
Paris 14     64846
Paris 09     61152
Paris 03     52893
Paris 04     46020
Paris 08     37317
Paris 05     32249
Paris 02     24986
Paris 01     23680
Paris 07     22705
Paris 06     21623
Paris 00       102
Paris 82         4
Paris 44         3
Name: count, dtype: int64

In [25]:
df['arrondissement'].dtypes

dtype('int64')

In [26]:
df['arrondissement'].unique

<bound method Series.unique of 0          15
1          14
2          18
3          19
4          10
           ..
1474280    11
1474281    13
1474282    11
1474283    15
1474284    13
Name: arrondissement, Length: 1474285, dtype: int64>

In [27]:
df['arrondissement'].sample

<bound method NDFrame.sample of 0          15
1          14
2          18
3          19
4          10
           ..
1474280    11
1474281    13
1474282    11
1474283    15
1474284    13
Name: arrondissement, Length: 1474285, dtype: int64>

In [28]:
df['arrondissement'].value_counts().unique

<bound method Series.unique of arrondissement
18    132190
20    131858
17    125147
15    121025
19    113396
11    112121
10    105243
12     88825
13     80375
16     76525
14     64846
9      61152
3      52893
4      46020
8      37317
5      32249
2      24986
1      23680
7      22705
6      21623
0        102
82         4
44         3
Name: count, dtype: int64>

In [29]:
df['adresse'].value_counts().unique

<bound method Series.unique of adresse
Bois de Vincennes Route de la Pyramide, 75012 PARIS    835
2 Rue Pavée, 75004 PARIS                               413
21 Rue Pavée, 75004 PARIS                              374
13 Rue des Amiraux, 75018 PARIS                        354
2 Rue des Quatre-Fils, 75003 PARIS                     330
                                                      ...
172  Avenue d'Italie, 75013 PARIS                        1
25 rue du Colonel Moll, 75017 PARIS                      1
75b rue des Entrepreneurs, 75015 PARIS                   1
68 Rue des Belles Feuilles, 75016 PARIS                  1
184 avenue Victor Hugo, 75116 PARIS                      1
Name: count, Length: 207878, dtype: int64>

In [30]:
df['adresse'].isnull()

0          False
1          False
2          False
3          False
4          False
           ...
1474280    False
1474281    False
1474282    False
1474283    False
1474284    False
Name: adresse, Length: 1474285, dtype: bool

In [31]:
df['adresse'].isnull().sum()

np.int64(0)