In [1]:
import pandas as pd
import numpy as np

In [3]:
df= pd.read_csv("../data/terrasses-autorisations.csv", sep=";")

In [4]:
df.head(10)

,typologie,adresse,arrondissement,nom_enseigne,nom_societe,siret,longueur,largeur,periode_installation,lien_affichette,geo_shape,geo_point_2d
0,TERRASSE OUVERTE,31BIS RUE NATIONALE,75013.0,PHO INDOCHINE,NaN,9.199596e+13,3.00,0.90,NaN,https://eudonet-terrasses.apps.paris.fr/xrm/at...,"{""coordinates"": [2.3680158143043655, 48.824004...","48.82400471029666, 2.3680158143043655"
1,TERRASSE OUVERTE,4 RUE DE LONDRES,75009.0,WHATEVER,NaN,4.390775e+13,8.70,0.90,NaN,https://eudonet-terrasses.apps.paris.fr/xrm/at...,"{""coordinates"": [2.3303737262232986, 48.876805...","48.876805568416614, 2.3303737262232986"
2,ETALAGE,113 BOULEVARD DAVOUT,75020.0,TOUNSI GELATO,NaN,8.300001e+13,7.00,1.15,NaN,https://eudonet-terrasses.apps.paris.fr/xrm/at...,"{""coordinates"": [2.4097961905513556, 48.856679...","48.856679379299834, 2.4097961905513556"
3,TERRASSE FERMÉE,79 AVENUE DE SEGUR,75015.0,FÉLIX RESTAURANT,NaN,8.193063e+13,12.12,2.00,NaN,https://eudonet-terrasses.apps.paris.fr/xrm/at...,"{""coordinates"": [2.3059667425651407, 48.847399...","48.84739977647407, 2.3059667425651407"
4,TERRASSE OUVERTE,97 RUE DE L AMIRAL MOUCHEZ,75013.0,LE GENTILLY.,NaN,9.524156e+13,4.00,0.60,NaN,https://eudonet-terrasses.apps.paris.fr/xrm/at...,"{""coordinates"": [2.344663989631858, 48.8196212...","48.81962129018752, 2.344663989631858"
5,TERRASSE OUVERTE,300 RUE DES PYRENEES,75020.0,LIN,NaN,9.214091e+13,5.30,1.00,NaN,https://eudonet-terrasses.apps.paris.fr/xrm/at...,"{""coordinates"": [2.3918611099763463, 48.872111...","48.87211190253334, 2.3918611099763463"
6,TERRASSE FERMÉE,2 RUE DE CRONSTADT,75015.0,AIGLE ROYAL,NaN,7.536931e+13,9.76,1.25,NaN,https://eudonet-terrasses.apps.paris.fr/xrm/at...,"{""coordinates"": [2.3025282980583968, 48.835233...","48.835233857836286, 2.3025282980583968"
7,TERRASSE OUVERTE,8 AVENUE FRANKLIN D ROOSEVELT,75008.0,FRANKLIN RESTAURATION,NaN,4.147264e+13,2.60,2.12,NaN,https://eudonet-terrasses.apps.paris.fr/xrm/at...,"{""coordinates"": [2.310207714210082, 48.8705649...","48.87056496613838, 2.310207714210082"
8,PLANCHER MOBILE,10 RUE SAINT ANTOINE,75016.0,LENOTRE,NaN,6.620545e+13,4.85,2.10,NaN,https://eudonet-terrasses.apps.paris.fr/xrm/at...,"{""coordinates"": [2.3670504274824173, 48.853684...","48.85368415520967, 2.3670504274824173"
9,TERRASSE OUVERTE,48 RUE D ARGOUT,75002.0,LA BISE,NaN,9.013428e+13,4.10,0.60,NaN,https://eudonet-terrasses.apps.paris.fr/xrm/at...,"{""coordinates"": [2.3437070050537465, 48.865938...","48.865938025309525, 2.3437070050537465"

In [6]:
df.tail(10)

,typologie,adresse,arrondissement,nom_enseigne,nom_societe,siret,longueur,largeur,periode_installation,lien_affichette,geo_shape,geo_point_2d
24197,CONTRE TERRASSE ESTIVALE SUR STATIONNEMENT,36 RUE D'AUTEUIL,75016.0,GINETTE,NaN,9.286980e+13,6.00,1.7,NaN,NaN,"{""coordinates"": [2.265940208994254, 48.8476838...","48.84768382204322, 2.265940208994254"
24198,CONTRE TERRASSE ESTIVALE SUR TROTTOIR FACE À L...,2 PLACE DU CHATELET,75004.0,LE SARAH BERNHARDT,NaN,5.520732e+13,4.20,1.3,NaN,https://eudonet-terrasses.apps.paris.fr/xrm/at...,"{""coordinates"": [2.3477887644808964, 48.857518...","48.85751828362271, 2.3477887644808964"
24199,TERRASSES OUVERTES SUR TROTTOIR,307 RUE DU FAUBOURG SAINT ANTOINE,75011.0,EXTRA OLD CAFE,NaN,4.312229e+13,8.00,2.5,NaN,NaN,"{""coordinates"": [2.392748350781821, 48.8489770...","48.84897700854839, 2.392748350781821"
24200,TERRASSES OUVERTES SUR TROTTOIR,26 RUE DU DOCTEUR MAGNAN,NaN,L'AGE D'OR,NaN,5.148130e+13,5.00,0.3,NaN,https://eudonet-terrasses.apps.paris.fr/xrm/at...,"{""coordinates"": [2.3598923261567872, 48.826461...","48.82646103790871, 2.3598923261567872"
24201,CONTRE TERRASSE ESTIVALE SUR STATIONNEMENT,14 RUE D'ODESSA,75014.0,TOYAMA,NaN,4.947389e+13,6.00,1.7,NaN,NaN,"{""coordinates"": [2.3245252597315553, 48.842249...","48.84224904284779, 2.3245252597315553"
24202,TERRASSES OUVERTES SUR TROTTOIR,13 AVENUE BUGEAUD,75116.0,SORELLA,NaN,9.537433e+13,6.00,1.0,NaN,https://eudonet-terrasses.apps.paris.fr/xrm/at...,"{""coordinates"": [2.283129653155403, 48.8700882...","48.87008826614744, 2.283129653155403"
24203,TERRASSES OUVERTES SUR TROTTOIR,89 AVENUE EMILE ZOLA,75015.0,NUMA,NaN,9.341054e+13,6.20,1.0,NaN,NaN,"{""coordinates"": [2.288016624300903, 48.8467404...","48.846740490025994, 2.288016624300903"
24204,CONTRE TERRASSE ESTIVALE SUR STATIONNEMENT,1 RUE DE GRIBEAUVAL,NaN,RACINES DES PRES,NaN,8.217990e+13,7.00,1.8,NaN,https://eudonet-terrasses.apps.paris.fr/xrm/at...,"{""coordinates"": [2.3270276296645513, 48.856192...","48.85619280168554, 2.3270276296645513"
24205,TERRASSES OUVERTES SUR TROTTOIR,14 RUE DU PONT NEUF,75001.0,JJAN,NaN,9.791025e+13,8.85,1.5,NaN,NaN,"{""coordinates"": [2.344311876801296, 48.8601413...","48.86014130275226, 2.344311876801296"
24206,TERRASSE ESTIVALE SUR TROTTOIR FACE À LA DEVAN...,117 AVENUE DE LA BOURDONNAIS,75007.0,HÔTEL LE CERCLE,NaN,4.340117e+13,6.00,2.6,NaN,NaN,"{""coordinates"": [2.3048464633170025, 48.854766...","48.85476603146032, 2.3048464633170025"

In [ ]:
df.shape

(24207, 12)

In [8]:
df.value_counts

<bound method DataFrame.value_counts of                                                typologie  \
0                                       TERRASSE OUVERTE
1                                       TERRASSE OUVERTE
2                                                ETALAGE
3                                        TERRASSE FERMÉE
4                                       TERRASSE OUVERTE
...                                                  ...
24202                    TERRASSES OUVERTES SUR TROTTOIR
24203                    TERRASSES OUVERTES SUR TROTTOIR
24204         CONTRE TERRASSE ESTIVALE SUR STATIONNEMENT
24205                    TERRASSES OUVERTES SUR TROTTOIR
24206  TERRASSE ESTIVALE SUR TROTTOIR FACE À LA DEVAN...

                            adresse  arrondissement      nom_enseigne  \
0               31BIS RUE NATIONALE         75013.0     PHO INDOCHINE
1                  4 RUE DE LONDRES         75009.0          WHATEVER
2              113 BOULEVARD DAVOUT         75020.0     TOUNSI GELATO
3                79 AVENUE DE SEGUR         75015.0  FÉLIX RESTAURANT
4        97 RUE DE L AMIRAL MOUCHEZ         75013.0      LE GENTILLY.
...                             ...             ...               ...
24202             13 AVENUE BUGEAUD         75116.0           SORELLA
24203          89 AVENUE EMILE ZOLA         75015.0              NUMA
24204           1 RUE DE GRIBEAUVAL             NaN  RACINES DES PRES
24205           14 RUE DU PONT NEUF         75001.0              JJAN
24206  117 AVENUE DE LA BOURDONNAIS         75007.0   HÔTEL LE CERCLE

      nom_societe         siret  longueur  largeur periode_installation  \
0             NaN  9.199596e+13      3.00     0.90                  NaN
1             NaN  4.390775e+13      8.70     0.90                  NaN
2             NaN  8.300001e+13      7.00     1.15                  NaN
3             NaN  8.193063e+13     12.12     2.00                  NaN
4             NaN  9.524156e+13      4.00     0.60                  NaN
...           ...           ...       ...      ...                  ...
24202         NaN  9.537433e+13      6.00     1.00                  NaN
24203         NaN  9.341054e+13      6.20     1.00                  NaN
24204         NaN  8.217990e+13      7.00     1.80                  NaN
24205         NaN  9.791025e+13      8.85     1.50                  NaN
24206         NaN  4.340117e+13      6.00     2.60                  NaN

                                         lien_affichette  \
0      https://eudonet-terrasses.apps.paris.fr/xrm/at...
1      https://eudonet-terrasses.apps.paris.fr/xrm/at...
2      https://eudonet-terrasses.apps.paris.fr/xrm/at...
3      https://eudonet-terrasses.apps.paris.fr/xrm/at...
4      https://eudonet-terrasses.apps.paris.fr/xrm/at...
...                                                  ...
24202  https://eudonet-terrasses.apps.paris.fr/xrm/at...
24203                                                NaN
24204  https://eudonet-terrasses.apps.paris.fr/xrm/at...
24205                                                NaN
24206                                                NaN

                                               geo_shape  \
0      {"coordinates": [2.3680158143043655, 48.824004...
1      {"coordinates": [2.3303737262232986, 48.876805...
2      {"coordinates": [2.4097961905513556, 48.856679...
3      {"coordinates": [2.3059667425651407, 48.847399...
4      {"coordinates": [2.344663989631858, 48.8196212...
...                                                  ...
24202  {"coordinates": [2.283129653155403, 48.8700882...
24203  {"coordinates": [2.288016624300903, 48.8467404...
24204  {"coordinates": [2.3270276296645513, 48.856192...
24205  {"coordinates": [2.344311876801296, 48.8601413...
24206  {"coordinates": [2.3048464633170025, 48.854766...

                                 geo_point_2d
0       48.82400471029666, 2.3680158143043655
1      48.876805568416614, 2.3303737262232986
2      48.856679379299834, 2.4097961905513556
3       48.84739977647407, 2.3059667425651407
4        48.81962129018752, 2.344663989631858
...                                       ...
24202    48.87008826614744, 2.283129653155403
24203   48.846740490025994, 2.288016624300903
24204   48.85619280168554, 2.3270276296645513
24205    48.86014130275226, 2.344311876801296
24206   48.85476603146032, 2.3048464633170025

[24207 rows x 12 columns]>

In [9]:
df.isnull().sum()

typologie                  10
adresse                     8
arrondissement            848
nom_enseigne              737
nom_societe             23473
siret                     924
longueur                   16
largeur                    15
periode_installation    23482
lien_affichette          5443
geo_shape                   0
geo_point_2d                0
dtype: int64

In [10]:
df.columns

Index(['typologie', 'adresse', 'arrondissement', 'nom_enseigne', 'nom_societe',
       'siret', 'longueur', 'largeur', 'periode_installation',
       'lien_affichette', 'geo_shape', 'geo_point_2d'],
      dtype='str')

In [11]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 24207 entries, 0 to 24206
Data columns (total 12 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   typologie             24197 non-null  str
 1   adresse               24199 non-null  str
 2   arrondissement        23359 non-null  float64
 3   nom_enseigne          23470 non-null  str
 4   nom_societe           734 non-null    str
 5   siret                 23283 non-null  float64
 6   longueur              24191 non-null  float64
 7   largeur               24192 non-null  float64
 8   periode_installation  725 non-null    str
 9   lien_affichette       18764 non-null  str
 10  geo_shape             24207 non-null  str
 11  geo_point_2d          24207 non-null  str
dtypes: float64(4), str(8)
memory usage: 2.2 MB

In [14]:
df.dtypes

typologie                   str
adresse                     str
arrondissement          float64
nom_enseigne                str
nom_societe                 str
siret                   float64
longueur                float64
largeur                 float64
periode_installation        str
lien_affichette             str
geo_shape                   str
geo_point_2d                str
dtype: object

In [15]:
df['arrondissement'].dtypes

dtype('float64')

In [16]:
df['arrondissement'].unique

<bound method Series.unique of 0        75013.0
1        75009.0
2        75020.0
3        75015.0
4        75013.0
          ...
24202    75116.0
24203    75015.0
24204        NaN
24205    75001.0
24206    75007.0
Name: arrondissement, Length: 24207, dtype: float64>

In [20]:
df['typologie'].unique

<bound method Series.unique of 0                                         TERRASSE OUVERTE
1                                         TERRASSE OUVERTE
2                                                  ETALAGE
3                                          TERRASSE FERMÉE
4                                         TERRASSE OUVERTE
                               ...
24202                      TERRASSES OUVERTES SUR TROTTOIR
24203                      TERRASSES OUVERTES SUR TROTTOIR
24204           CONTRE TERRASSE ESTIVALE SUR STATIONNEMENT
24205                      TERRASSES OUVERTES SUR TROTTOIR
24206    TERRASSE ESTIVALE SUR TROTTOIR FACE À LA DEVAN...
Name: typologie, Length: 24207, dtype: str>

In [21]:
df['arrondissement'].value_counts().unique

<bound method Series.unique of arrondissement
75015.0    1713
75010.0    1682
75011.0    1554
75017.0    1546
75018.0    1509
75012.0    1385
75009.0    1351
75014.0    1296
75005.0    1275
75020.0    1180
75008.0    1180
75013.0    1063
75019.0     904
75004.0     890
75001.0     847
75006.0     761
75007.0     696
75002.0     672
75016.0     653
75116.0     634
75003.0     568
Name: count, dtype: int64>

In [22]:
df['adresse'].value_counts().unique

<bound method Series.unique of adresse
161 QUAI DE VALMY                15
3 RUE GEORGES PICQUART           11
4 PLACE TATTEGRAIN               11
108 BOULEVARD DU MONTPARNASSE    10
1 RUE CHAPTAL                    10
                                 ..
20 RUE DE LA REYNIE               1
116 RUE DU CHEMIN VERT            1
46 AVENUE EMILE ZOLA              1
36 RUE D'AUTEUIL                  1
117 AVENUE DE LA BOURDONNAIS      1
Name: count, Length: 14982, dtype: int64>

In [27]:
df['adresse'].isnull().sum()

np.int64(0)

In [26]:
df = df.dropna(subset=['adresse'])